### PR TITLE
Update Vietnamese/strings_vi

### PR DESCRIPTION
**Pull request by Tuan1-2-3**

### CODE REVIEW

**Comment by PranshulGG** [comment]
Missing strings

**Comment by Tuan1-2-3** [comment]
What strings are you mentioning, @PranshulGG ?

**Comment by PranshulGG** [comment]
> What strings are you mentioning, @PranshulGG ?

`    "precipitation": "Precipitation",
    "wind": "Wind",
    "pollen": "Pollen",
    "grass":"Grass",
    "tree": "Tree",
    "weed": "Weed",
    "quick_summary": "Quick summary",
    "temperature_animation": "Temperature animation",
    "language": "Language",
    "translate_this_app": "Translate this app",
    "contributors": "Contributors",
    "contributors_sub": "View people who contributed to this project",
    "version": "Version",
    "third_party_licenses": "Third party licenses",
    "clothing_activity": "Clothing and Activity",
    "get_clothing_suggestions": "Get your Clothing and Activity Suggestions",
    "day": "Day",
    "evening": "Evening",
    "night": "Night",
    "wind_gust": "Wind gust",
    "rain_expected_to_continue": "Rain is expected to continue for the next few hours",
    "rain_likely_tomorrow_around": "Rain likely tomorrow around",
    "rain_likely_around": "Rain likely around",
    "weather_alerts": "Weather alerts"`

**Comment by Tuan1-2-3** [comment]
OK! I will add it.

**Comment by PranshulGG** [comment]
I'll close this because Crowdin is done.

**Pull request closed without merging**
